openapi: 3.0.0
x-service-type: 2
info:
  title: 'games'
  description: 'Сервис для создания и хранения игр'
  version: 1.0.0
servers:
  - url: 'https://games.abdulovdb.team/'
    description: Адрес для запросов от хоста к k8s
  - url: 'http://games:{port}/'
    description: Внутренний адрес k8s для разработки
    x-env: development
    variables:
      port:
        enum:
          - '10000'
        default: '10000'
  - url: 'http://games:{port}/'
    description: Боевой внутренний адрес k8s
    x-env: production
    variables:
      port:
        enum:
          - '10000'
        default: '10000'
tags:
  - name: 'games'
    description: 'Методы для работы со списком игр'

paths:
  /games/get:
    $ref: './methods/games/get.yml'
  /games/create:
    $ref: './methods/games/create.yml'
