openapi: 3.0.0
x-service-type: 2
info:
  title: 'users'
  description: 'Сервис пользователей'
  version: 1.0.0
servers:
  - url: 'https://users.abdulovdb.team/'
    description: Адрес для запросов от хоста к k8s
  - url: 'http://users:{port}/'
    description: Внутренний адрес k8s для разработки
    x-env: development
    variables:
      port:
        enum:
          - '10001'
        default: '10001'
  - url: 'http://users:{port}/'
    description: Боевой внутренний адрес k8s
    x-env: production
    variables:
      port:
        enum:
          - '10001'
        default: '10001'
tags:
  - name: 'users'
    description: 'Методы для работы с пользователями'

paths:
  /users/get:
    $ref: './methods/users/get.yml'
